modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
[[mods]]
modId = "openlink_chmlfrp_extension"
version = "1.0.0"
displayName = "OpenLink Chmlfrp Extension"
logoFile="icon.png"
authors = "Yuang2714"
description = '''${mod_description}'''

[[dependencies.openlink_chmlfrp_extension]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.openlink_chmlfrp_extension]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.20.4]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.openlink_chmlfrp_extension]]
modId = "openlink"
mandatory = true
versionRange = "[1.1.0,)"
side = "CLIENT"